name: Deploy Hexo

on:
  push:
    branches:
      - master  # 根据你的分支调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Hexo
        run: npm run build  # 或者 hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: ycxh/hexo123456.github.io
          publish_dir: ./public
          publish_branch: master
